### ISSUE TITLE
Make Data.IP.Addr public module

### ISSUE THREAD

**Issue by wdanilo** [kazu-yamamoto/iproute#12]
Hello! I would like to request to make the `Data.IP.Addr` module public. I would like to use the parsing functions to create custom `read` method that would fallback to name reading, like `"haskell.org"` if not matched with `IPv{4,6}` address.

**Comment by kazu-yamamoto** [comment]
OK. Would you do it by yourself and give me a pull request? Instead of export `Addr` directly, I would like to do:

- Create a new module `Internal`
- Import what you want in `Intrernal` and re-export them

**Comment by kazu-yamamoto** [comment]
Already solved. Let's close.
