### ISSUE TITLE
Inverted makeAddrRange function

### ISSUE THREAD

**Issue by ondrap** [kazu-yamamoto/iproute#15]
I am trying to solve a  problem of comparing IPv4 with IPv4-embedded-in-IPv6 address. I am not sure if the Eq Class should say  ```IPv4 "127.0.0.1" == IPv6 "::ffff:127.0.0.1"``` (maybe it should? - in that case it should work similarly with all the operators?) 
However I would need a way to at least convert it. This is possible for IP type, but it is impossible for the AddrRange, as the internals of the type are not publicly accessible. Would it be possible to add a function that would be like ```AddrRange a -> (a, Int) ```?

**Comment by kazu-yamamoto** [comment]
I agree. `IPv4 "127.0.0.1" == IPv6 "::ffff:127.0.0.1"` should be True.

I would like to have the following public functions:
- `isEmbedded :: IPv6Addr -> Bool`
- `extractIPv4Addr :: IPv6Addr -> IPv4Addr`

Would you take care of them?

**Comment by ondrap** [comment]
I have added the equality check in ondrap@11365eed0ced8c01c00a6990134d971373568b4f , renamed the "unmake" function. What I am somewhat missing is the ```isMatchedTo``` function which does not work on the AddrRange, which would be nice (I have added ```ipv4RangeToIpv6``` function which helps). I think it is better to do the conversion IPv4 -> IPv6 rather than the other way round.

**Comment by kazu-yamamoto** [comment]
Do you want to use `isMatchedTo` to `IPv4` and `AddrRange IPv6`? If so, is it good enough to convert `IPv4` to `IPv6` by `ipv4ToIpv6`?

**Comment by ondrap** [comment]
I have already created a function that converts ipv4range to ipv6 range, it is probably enough the way it is.

**Comment by kazu-yamamoto** [comment]
So, what I should do is wait for your pull request, right?

**Comment by ondrap** [comment]
It is all in the pull request #16, is it OK this way?

**Comment by kazu-yamamoto** [comment]
Sorry, I did not understand your intention. Merged.

BTW: what is going on for `isMatchedTo`?

**Comment by ondrap** [comment]
I would leave it the way it is. It would be needed to make IP instance of Addr, which wouldn't make much sense because of the 'masked' function which is depndent on the type of IP address. If somebody needs it (I do...) it is easy to convert the IPv4 part of the equation to IPv6 and run the isMatchedTo on the result. I will close this issue.
