### ISSUE TITLE
Split Data.IP and Data.IP.RouteTable into separate packages?

### ISSUE THREAD

**Issue by ppetr** [kazu-yamamoto/iproute#32]
Module `Data.IP` is very convenient for working with addresses (rather than low-level `Network.SockAddr`), but for most of such use-cases module `Data.IP.RouteTable` is redundant. Splitting these two into separate packages would be definitely useful and attract more users to `Data.IP`.

I'm happy to contribute, if we reach an agreement on this.

**Comment by kazu-yamamoto** [comment]
I have experience on splitting the network package into network and network-uri. The motivation in this case is that `Network.URI` depends on `parsec` which depends on `text`, which is really large package. When we try to install the network package, it take much time.

When we split the network package, we prepared a flag to maintain backward compatibility, which was a boring job. I understand that you feel that `Data.IP.RouteTable` is redundant. But I believe that the module is really costless. 

At this moment, I cannot see good reasons to pay splitting cost.

**Comment by kazu-yamamoto** [comment]
Please reopen this if necessary.
